name: Add nvim config

on:
  workflow_dispatch:
    inputs:
      owner:
        description: "Config owner"
        required: true
      url:
        description: "Config repo URL"
        required: true

jobs:
  add-nvim-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check if owner exists
        run: |
          OWNER="${{ github.event.inputs.owner }}"
          if jq -e --arg owner "$OWNER" '.configs | has($owner)' configs.json > /dev/null; then
            echo "Owner $OWNER already exists in nvim.json"
            exit 1
          fi

      - name: Check if branch exists
        if: success()
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/add-nvim-config-${{ github.event.inputs.owner }}; then
            echo "Branch add-nvim-config-${{ github.event.inputs.owner }} already exists"
            exit 1
          fi

      - name: Create branch
        if: success()
        run: |
          git checkout -b add-nvim-config-${{ github.event.inputs.owner }}

      - name: Add config
        run: |
          OWNER="${{ github.event.inputs.owner }}"
          URL="${{ github.event.inputs.url }}"

          jq --arg owner "$OWNER" --arg url "$URL" '.configs[$owner] = $url' configs.json > tmp.json && mv tmp.json configs.json

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add configs.json
          git commit -m "Add nvim config for ${{ github.event.inputs.owner }}"
          git push --set-upstream origin add-nvim-config-${{ github.event.inputs.owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          gh pr create \
            --title "Add nvim config for ${{ github.event.inputs.owner }}" \
            --body "This PR adds a new nvim config for ${{ github.event.inputs.owner }}." \
            --head add-nvim-config-${{ github.event.inputs.owner }} \
            --label "add-nvim-config" \
            --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
